services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    restart: unless-stopped

  script:
    build: ./EnergyMeter
    privileged: true
    restart: unless-stopped
    
  dashboard:
    build: ./Dashboard
    ports:
      - "80:80"
    restart: unless-stopped