services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
  script:
    build: ./EnergyMeter
    privileged: true
  dashboard:
    build: ./Dashboard
    ports:
      - "80:80"